version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "${PG_PORT}:${PG_PORT}"
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    networks:
      - api-network
    restart: 'always'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USERNAME} -d ${PG_DATABASE}" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes:
      - db:/var/lib/postgresql/data
      - ./src/db/queries/create-users-table.sql:/docker-entrypoint-initdb.d/create-users-table.sql
      - ./src/db/queries/insert-users.sql:/docker-entrypoint-initdb.d/insert-users-table.sql

  api:
    build: .
    container_name: nest-api
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./nest-api:/app
    environment:
      PG_HOST: db
      PG_PORT: ${PG_PORT}
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      NODE_ENV: ${NODE_ENV}
    networks:
      - api-network

volumes:
  db:

networks:
  api-network:


